models.py
from sqlalchemy import create_engine, Column, Integer, String, Text, BLOB, or_
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker, validates

engine = create_engine ('postgresql://postgres:mypgdbpass@postgres:5432/food_website')

Base = declarative_base()

class FoodInfo(Base):
    __tablename__ = 'foodinfo'
    id = Column(Integer, primary_key=True)
    name = Column(String)
    category_id = Column(Integer)
    nickname = Column(String)
    taste = Column(String)
    efficacy = Column(Text)
    suitable_for = Column(Text)
    not_suitable_for = Column(Text)
    note = Column(Text)
    image = Column(BLOB)
    thumbnail = Column(BLOB)

class Food_Category(Base):
    __tablename__ = 'food_category'
    id = Column(Integer, primary_key=True)
    name = Column(String)    


Session = sessionmaker(bind=engine)
session = Session()

def searchText(search_query):
    return session.query(FoodInfo).filter(
        or_(FoodInfo.name.ilike(f"%{search_query}%"),
            FoodInfo.nickname.ilike(f"%{search_query}%"),
            FoodInfo.efficacy.ilike(f"%{search_query}%"),
            FoodInfo.suitable_for.ilike(f"%{search_query}%"),
            FoodInfo.not_suitable_for.ilike(f"%{search_query}%"),
            FoodInfo.note.ilike(f"%{search_query}%")
        )).all()

def get_categoryList():
    return session.query(Food_Category).all()

def get_categoryName(category_id):
    return session.query(Food_Category).get(category_id)

def get_food(food_id):
    return session.query(FoodInfo).get(food_id)

def get_foodList(category_id):
    return session.query(FoodInfo).filter_by(category_id=category_id).all()

app.py
from flask import Flask
from routes import bp

app = Flask(__name__)
app.register_blueprint(bp)

if __name__ == '__main__':
    app.run()

routes.py
from flask import Blueprint, render_template, request, session
from models import get_categoryList, get_foodList, get_categoryName, get_food, searchText

bp = Blueprint('food', __name__)

@bp.route('/')
def index():
    return render_template('index.html')

@bp.route('/intro')
def intro():
    return render_template('intro.html')

@bp.route('/search', methods=['GET', 'POST'])
def search():
    if request.method == 'POST':
        search_query = request.form['query']
        foods = searchText(search_query)
        return render_template('search.html', foods=foods, search_query=search_query)
    return render_template('search.html')

# @bp.route('/<int:food_id>')
# def details(food_id):
#     food = FoodInfo.query.get_or_404(food_id)
#     return render_template('details.html', food=food)

@bp.route('/foodcategories')
def food_categories():
    foodCategories = get_categoryList()
    return render_template('foodcategories.html', foodCategories=foodCategories)

    # conn = get_db_connection()
    # foodCategories = conn.execute('SELECT * FROM Food_Category').fetchall()
    # conn.close()
    # return render_template('foodcategories.html', foodCategories=foodCategories)

@bp.route('/foodcategories/foods/<int:category_id>')
def food_by_categories(category_id):
    foods = get_foodList(category_id)
    category_name = get_categoryName(category_id)
    return render_template('foods.html', foods=foods, category_name=category_name.name)

# @app.route('/foodcategories/foods/<int:category_id>')
# def food_by_categories(category_id):
#     foods = get_foodList(category_id)
#     category_name = get_CategoryName(category_id)
#     return render_template('foods.html', foods=foods, category_name=category_name['name'])

@bp.route('/foodcategories/foods/<int:category_id>/<int:food_id>')
def fooddetails(category_id,food_id):
    food = get_food(food_id)
    return render_template('fooddetails.html', food=food)

# @app.route('/foodcategories/foods/<int:category_id>/<int:food_id>')
# def fooddetails(category_id,food_id):
#     food = get_food(food_id)
#     return render_template('foodDetails.html', food=food)

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" context="text/html">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">
        <a class="navbar-brand" href="{{ url_for('food.index')}}">飲食宜忌</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('food.intro')}}">緒論</a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{{ url_for('food.food_categories')}}">榖 果 菜 飲食宜忌</a>
            </li>
            </ul>
            <form class="form-inline ml-auto" action="{{ url_for('food.search')}}" method="POST">
                <input class="form-control mr-sm-2" type="search" name="query" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>
    <div class="container">
        {% block content %} {% endblock %}
    </div>
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

templates/foodcategories.html
{% extends 'base.html' %}

{% block content %}
    <h1>{% block title %} 榖 果 菜 飲食宜忌 {% endblock %}</h1>
    {% for category in foodCategories %}
    <a href="{{ url_for('food.food_by_categories', category_id=category['id']) }}">
        <h2>{{ category['name'] }}</h2>
    </a>
    
    {% endfor %}
{% endblock %}

templates/fooddetails.html
{% extends 'base.html' %}

{% block content %}
<!-- Include JavaScript function to decode Base64 image data -->
<!-- <script>
    function decodeBase64Image(encodedData) {
        var byteString = atob(encodedData);
        var arrayBuffer = new ArrayBuffer(byteString.length);
        var uint8Array = new Uint8Array(arrayBuffer);
        for (var i = 0; i < byteString.length; i++) {
            uint8Array[i] = byteString.charCodeAt(i);
        }
        var blob = new Blob([arrayBuffer], {type: 'image/jpeg'});
        return URL.createObjectURL(blob);
    }
</script> -->
<hr>
    <h1>{% block title %} {{ food['name'] }}{% endblock %}</h1>
        <p>【俗名】{{ food['nickname'] }}</p>
        <p>【性味】{{ food['taste'] }}</p>
        <p>【功效】{{ food['efficacy'] }}</p>
        <p>【宜食】{{ food['suitable_for'] }}</p>
        <p>【忌食】{{ food['not_suitable_for'] }}</p>
        <p>【按語】{{ food['note'] }}</p>
        
        <!-- <img id="foodImage" alt="Food Image" style="display: none;">
        <hr>
        <script>
            // Decode Base64 image data and set as src attribute
            var foodImageData = "{{ food['image'] }}";
            if (foodImageData){
                var decodedImageData = decodeBase64Image(foodImageData);
                document.getElementById('foodImage').src = decodedImageData;
                document.getElementById('foodImage').style.display = 'block';
            }
        </script> -->

{% endblock %}

templates/foods.html
{% extends 'base.html' %}

{% block content %}
    <h1>{% block title %} {{category_name}} {% endblock %}</h1>
    {% for food in foods %}
    <a href="{{ url_for('food.fooddetails', food_id=food['id'], category_id=food['category_id']) }}">
        <h2>{{ food['name'] }}</h2>
    </a>
    
    {% endfor %}
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>{% block title %} 飲食宜忌-緒論 {% endblock %}</h1>
    <p>中國人的傳統飲食宜忌觀，是通過幾千年來人民大眾經歷了無數次的親身生活實踐和歷代醫家長期的醫療臨床實踐逐漸總結發展而形成的，它積累了許許多多醫藥學家、養生學家、儒家、道家、佛家以及廣大民眾的寶貴經驗，尤其是歷史上的醫學家們根據中國傳統醫學理論，把這些飲食宜忌的豐富經驗不斷上升到食醫理論的高度來認識和完善。可以說,中國醫學理論是中國傳統飲食宜忌理論的基礎，其中包含了“食藥同源”之說、食物性味歸經理論、飲食宜忌的辨證觀、以及民間“發物”忌口等內容。如果能了解或熟知這些基礎理論，就能掌握好飲食宜忌的總體原則和對飲食宜忌的靈活運用。</p>
    <p>重點聲明：
        本資料內容抄自於【中国传统饮食宜忌全书】
        飲食宜忌全書出自於《王焕华、倪慧珠編著》
        參考本資料內容的同時，請先購買原著作；
        《王焕华、倪慧珠編著》的
        【中国传统饮食宜忌全书】（ 修订本）
        由「江苏科学技术出版社」出版的“原著作”。
               本資料內容是以繁體中文為主，方便繁體中文的使用者，參考對照“原著作”。
               本抄錄內容是以（奶蛋素食者）的需求為出發點，因此，“原著作”的內容，非（奶蛋素食者）適宜的部分，一概不予抄錄。
               本資料內容是以配合對照“原著作”的參考使用，請勿作為“商業用途”。
               本資料內容僅供參考，不用於診斷、治療、治愈或預防任何病症或疾病。您了解本資料內容不能替代諮詢有執照的從業者。請就本資料內容中提出的建議，諮詢您自己的醫生或醫療保健專家。
           使用本資料內容即表示您接受本免責聲明。</p>
{% endblock %}

templates/search.html
{% extends 'base.html' %}

{% block content %}
<h1>{% block title %} Search {% endblock %}</h1>
{% if foods %}
<ul class="list-group">
    {% for food in foods %}
    <li class="list-group-item">
        <a href="{{ url_for('food.fooddetails', food_id=food['id'], category_id=food['category_id']) }}" class="h2"
            target="_blank">
            {{ food.name.replace(search_query, "<span style='background-color: yellow'>" + search_query +
                "</span>")|safe }}
        </a>
        {% if food.nickname %}
        <p class="pt-4">【俗名】{{ food.nickname.replace(search_query, "<span style='background-color: yellow'>" + search_query +
                "</span>")|safe }}</p>
        {% endif %}
        {% if food.efficacy %}
        <p>【功效】{{ food.efficacy.replace(search_query, "<span style='background-color: yellow'>" + search_query +
                "</span>")|safe }}</p>
        {% endif %}
        {% if food.suitable_for %}
        <p>【宜食】{{ food.suitable_for.replace(search_query, "<span style='background-color: yellow'>" + search_query +
                "</span>")|safe }}
        </p>
        {% endif %}
        {% if food.not_suitable_for %}
        <p>【忌食】{{ food.not_suitable_for.replace(search_query, "<span style='background-color: yellow'>" + search_query +
                "</span>")|safe }}
        </p>
        {% endif %}
        {% if food.note %}
        <p>【按語】{{ food.note.replace(search_query, "<span style='background-color: yellow'>" + search_query +
                "</span>")|safe }}
        </p>
        {% endif %}
    </li>
    {% endfor %}
</ul>
{% else %}
<p>No results found.</p>
{% endif %}
{% endblock %}